# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      cp sample.env .env

  - name: backend
    init: >
      cd ./backend &&
      npm i
    command: >
      cd ./backend &&
      npm run start:dev &&
      gp await-port 3000

  - name: frontend
    init: >
      cd ./frontend &&
      npm i
    command: >
      cd ./frontend &&
      npm run start &&
      gp await-port 4200
      
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: ignore
  - port: 4200
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
